### ISSUE TITLE
How to make the color black and better colorful for nvitop?

### ISSUE THREAD

**Issue by monajalal** [XuehaiPan/nvitop#10]
Thanks a lot for the great repo. Is there a way to make the background black and also the text colors nicer like yours?

<img width="1232" alt="Screen Shot 2021-12-14 at 2 54 57 PM" src="https://user-images.githubusercontent.com/1892917/146070126-2021fbf4-2008-4e87-8a28-474f65ff1f52.png">

**Comment by XuehaiPan** [comment]
> How to make the color black?

@monajalal Hi, I notice that you are using a light color scheme for your terminal. Do you mean only make the background color of `nvitop` to black, and change back to light color scheme when you exit and return to the terminal? Or change the whole terminal in dark mode too when you are not running `nvitop`.

1. dark background in `nvitop`, light background in terminal when not running `nvitop`.
2. always dark background when running and not running `nvitop`.

If the answer is the former one, I think I can add a new option like `--force-dark` to invert the foreground and the background color in light terminal. Otherwise, please change your terminal color scheme to a dark one. (See the last section of this comment)

------

> How to make the color better colorful for `nvitop`?

`nvitop` is developed on the `curses` module, which dynamically links to the system `curses` library (`ncurses` on Linux and `PDCurses` on Windows) at runtime. The `ncurses` library only supports 4-bits colors (_black, red, green, yellow, blue, magenta, cyan, white_).

`nvitop` does not support custom color themes yet. The GUI is rendered with command like _"add string `s` at `(x, y)` with color `red`"_. How red is the text looks is depending on your terminal color scheme:

![Screenshot colortheme](https://user-images.githubusercontent.com/16078332/146118441-89768f09-e8f7-4010-9b4a-0189b5a2014d.png)

`nvitop` doesn't support 24-bit true color in RGB tuple (we are using `ncurses` library though).

------

If you want to change your terminal color scheme, have a look the following repositories:

- [Mayccoll/Gogh](https://github.com/Mayccoll/Gogh)
- [mbadolato/iTerm2-Color-Schemes](https://github.com/mbadolato/iTerm2-Color-Schemes)

I'm using `Tomorrow Night Eighties` theme ([Gogh Gallary](https://mayccoll.github.io/Gogh/)).

**Comment by XuehaiPan** [comment]
@monajalal Does the above comment resolve your issue? And can we close this now?
