### ISSUE TITLE
[Question] `nvitop` runs non-dynamically inside `slurm` jobs

### ISSUE THREAD

**Issue by Saber813** [XuehaiPan/nvitop#33]
#### Runtime Environment

- Operating system and version: CentOS 7.4
- Python version: 3.8.13
- NVML version (driver version): 470.63
- `nvitop` version or commit: 0.7.2
- `python-ml-py` version: 11.450.51
- Locale: zh_CN.UTF-8

#### Current Behavior

Query the GPU usage of the computing node through Slurm, and the output is displayed **statically**

#### Images / Videos  

<img width="281" alt="b1d1d04c16ca93fbd7d9fa39a2ac273" src="https://user-images.githubusercontent.com/34484194/184590745-871684a0-d004-49ac-aecf-89ffe7b9f4d0.png">

**Comment by XuehaiPan** [comment]
Hi @Saber813, this is intentional behavior. Your `stdout` is not a TTY terminal with `slurm`.

https://github.com/XuehaiPan/nvitop/blob/a2f7c2425cf7f4edecbc1b701dd7ed979f5552fe/nvitop/cli.py#L268-L270

You should add `--pty` option to enable a pseudo-terminal:

![image](https://user-images.githubusercontent.com/16078332/184592620-ac110769-3695-4e6f-8f4a-5b55baa51de8.png)

**Comment by Saber813** [comment]
It works! Thank you, Closed
